services:
  api-prod:
    image: ghcr.io/andibalo/fortius-api:prod
    container_name: api-prod
    env_file: .env.prod
    networks:
      - proxy
      - prod-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-prod.rule=Host(`api.yourdomain.com`)"
      - "traefik.http.routers.api-prod.entrypoints=websecure"
      - "traefik.http.routers.api-prod.tls.certresolver=letsencrypt"
      - "traefik.http.services.api-prod.loadbalancer.server.port=8080"
    restart: unless-stopped
    depends_on:
      - postgres-prod

  postgres-prod:
    image: postgres:17-alpine
    container_name: postgres-prod
    env_file: .env.prod
    volumes:
      - /data/postgres-prod:/var/lib/postgresql/data
    networks:
      - prod-internal
    restart: unless-stopped

networks:
  proxy:
    external: true
  prod-internal:
    name: prod-internal
