services:
  api-stg:
    image: ghcr.io/andibalo/fortius-api:stg
    container_name: api-stg
    env_file: .env.stg
    networks:
      - proxy
      - stg-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-stg.rule=Host(`api-stg.yourdomain.com`)"
      - "traefik.http.routers.api-stg.entrypoints=websecure"
      - "traefik.http.routers.api-stg.tls.certresolver=letsencrypt"
      - "traefik.http.services.api-stg.loadbalancer.server.port=8080"
    restart: unless-stopped
    depends_on:
      - postgres-stg

  postgres-stg:
    image: postgres:17-alpine
    container_name: postgres-stg
    env_file: .env.stg
    volumes:
      - /data/postgres-stg:/var/lib/postgresql/data
    networks:
      - stg-internal
    restart: unless-stopped

networks:
  proxy:
    external: true
  stg-internal:
    name: stg-internal
